const departmentEmail = {
    'Computer Science & Engineering':'hodcse@nitt.edu',
    'Architecture':'hodarch@nitt.edu',
    'Civil Engineering':'hodcivil@nitt.edu',
    'Chemical Engineering':'hodchl@nitt.edu',
    'Chemistry':'hodchy@nitt.edu',
    'Computer Applications':'hodca@nitt.edu',
    'Electrical & Electronics Engineering':'hodeee@nitt.edu',
    'Electronics & Communication Engineering':'hodece@nitt.edu',
    'Energy and Environment':'hoddee@nitt.edu',
    'Humanities and Social Sciences':'hodhss@nitt.edu',
    'Instrumentation & Control Engineering':'hodice@nitt.edu',
    'Mechanical Engineering':'hodmech@nitt.edu',
    'Metallurgical & Materials Engineering':'hodmet@nitt.edu',
    'Management Studies':'hodmba@nitt.edu',
    'Physics':'hodphy@nitt.edu',
    'Mathematics':'hodmaths@nitt.edu',
    'Production Engineering':'hodprod@nitt.edu',
  }
  module.exports ={departmentEmail}